### ISSUE TITLE
problem installing nu-2.0.1.gem file

### ISSUE THREAD

**Issue by Dwrgi** [ProbstLab/uBin-helperscripts#6]
Hi,

I've been following the instructions to install UBin and got as far as installing all the gem files (which I had to do manually one by one) but I can't get the nu gem to install. I've downloaded it using wget and when I run the install local command I get the following error:

$ gem install --local nu-2.0.1.gem
ERROR:  While executing gem ... (ArgumentError)
    "\"CAMI_te" is not an octal string

This is my first time doing anything with Ruby and googling it didn't help. How do I fix this?

**Comment by till-bornemann** [comment]
Hi Dwrgi,

I suspect that the download of the gem file did not work correctly. The error indicates that the download malformed the ruby gem (it is expecting some octal string, ie i assume a string of length 8). The name you got (CAMI_te) suggests to me that you might have downloaded a hmtl or sth of the website instead of the actual file (since the CAMI dataset is supplied as a test dataset in this repository but it has nothing at all to do with the ruby gem).

 When you clone the repository with
`git clone https://github.com/ProbstLab/uBin-helperscripts.git` you should also download the nu-2.0.1.gem file along with the rest of the repository. Could you please try the command on the downloaded gem via the git clone command?

If the problem persists, could you send me the .gem file you are trying to install with the `gem install --local nu-2.0.1.gem` command via mail to till.bornemann@uni-duisburg-essen.de ? I'd then check if its looking as it should.

Best,
Till

Some references to the error:
https://github.com/rubygems/rubygems/issues/3344 

https://stackoverflow.com/questions/53962331/error-while-executing-gem-argumenterror-is-not-an-octal-string?rq=3 (though this is more for publishing gems, so more distantly related)

**Comment by Dwrgi** [comment]
Hi Till,
That seems to have worked once I copied the file to Home before running gem install.
Thanks!
